name: Plugin251
version: '${project.version}'
main: me.so_clownish.plugin251.Plugin251
api-version: 1.19
commands:
  rules:
    description: Rules
  website:
    aliases:
      - url
      - 251
      - 251SMP
    description: url